package models

import "time"

// Inventory represents the inventory items
type Inventory struct {
	ID              int       `json:"id"`
	CompanyID       int       `json:"company_id"`
	Name            string    `json:"name"`
	CategoryID      *int      `json:"category_id"` // Nullable
	IsArchived      bool      `json:"is_archived"`
	RetentionPeriod int       `json:"retention_period"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// TableName overrides the default table name generated by GORM
func (Inventory) TableName() string {
	return "inventory"
}
